SONATYPE_HOST=CENTRAL_PORTAL
RELEASE_SIGNING_ENABLED=true

POM_URL=https://github.com/maureenCindy/ihawu
POM_INCEPTION_YEAR=2026
POM_LICENSE_NAME=The Apache License, Version 2.0
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0
POM_LICENSE_DIST=repo

POM_SCM_URL=https://github.com/maureenCindy/ihawu
POM_SCM_CONNECTION=scm:git:git://github.com/maureenCindy/ihawu.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/maureenCindy/ihawu.git

POM_DEVELOPER_ID=maureencindy
POM_DEVELOPER_NAME=Maureen
POM_DEVELOPER_URL=https://github.com/maureenCindy
