blank_issues_enabled: false
contact_links:
  - name: Contribution Guidelines
    url: https://github.com/maureenCindy/ihawu/blob/main/CONTRIBUTING.md
    about: Please read our contribution guidelines before opening an issue
  - name: Discussions
    url: https://github.com/maureenCindy/ihawu/discussions
    about: For questions, ideas, and general discussions
